# -*- coding: utf-8 -*-
"""Data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r52ASNGWLjMWu6xB1Wa5RGeN59Fo_2PN
"""

import pandas as pd
from typing import List, Dict

def load_lob_csv(path: str) -> pd.DataFrame:
    """
    Load a single ticker's one-minute LOB snapshots CSV.
    Expected columns: time, bid_prices (list), bid_sizes (list), ask_prices (list), ask_sizes (list)
    """
    df = pd.read_csv(path, parse_dates=['time'])
    # Convert string-encoded lists to actual lists
    for col in ['bid_prices','bid_sizes','ask_prices','ask_sizes']:
        df[col] = df[col].apply(eval)
    # Compute mid-price
    df['mid_price'] = df.apply(lambda r: 0.5*(r['bid_prices'][0] + r['ask_prices'][0]), axis=1)
    return df

def load_all_tickers(paths: Dict[str, str]) -> Dict[str, pd.DataFrame]:
    """
    Given a dict ticker→csv_path, return ticker→DataFrame.
    """
    return {tic: load_lob_csv(p) for tic,p in paths.items()}