# -*- coding: utf-8 -*-
"""Model_fit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r52ASNGWLjMWu6xB1Wa5RGeN59Fo_2PN
"""

import numpy as np
import statsmodels.api as sm

def fit_power_law(x: np.ndarray, y: np.ndarray):
    """
    Fit y ≈ α x^γ via OLS on log-log:
      ln y = ln α + γ ln x + ε
    Returns (α, γ, R2).
    """
    X = sm.add_constant(np.log(x))
    model = sm.OLS(np.log(y), X).fit()
    lnα, γ = model.params
    return np.exp(lnα), γ, model.rsquared

def fit_alpha_time_varying(spread: np.ndarray, depth: np.ndarray, α_t: np.ndarray):
    """
    Fit α_t = β0 + β1*spread + β2*(1/depth)
    """
    X = np.column_stack([spread, 1/depth])
    X = sm.add_constant(X)
    model = sm.OLS(α_t, X).fit()
    return model.params, model.rsquared